const tableData = [
    {
        clientName: "Jane.D",
        clientPhone: "01960685765",
        clientMail: "admin@gmail.com",
        device: "Apple/Iphone 13pro",
        repairType: "Screen",
        date: "02/06/2026",
        slotNo: "1",
        startTime: "09:00",
    },
    {
        clientName: "Jane.D",
        clientPhone: "01960685765",
        clientMail: "admin@gmail.com",
        device: "Apple/Iphone 13pro",
        repairType: "Screen",
        date: "02/06/2026",
        slotNo: "1",
        startTime: "10:00",
    },
    {
        clientName: "Jane.D",
        clientPhone: "01960685765",
        clientMail: "admin@gmail.com",
        device: "Apple/Iphone 13pro",
        repairType: "Screen",
        date: "02/06/2026",
        slotNo: "1",
        startTime: "11:00",
    },
    {
        clientName: "Jane.D",
        clientPhone: "01960685765",
        clientMail: "admin@gmail.com",
        device: "Apple/Iphone 13pro",
        repairType: "Screen",
        date: "02/06/2026",
        slotNo: "1",
        startTime: "12:00",
    },
    {
        clientName: "Jane.D",
        clientPhone: "01960685765",
        clientMail: "admin@gmail.com",
        device: "Apple/Iphone 13pro",
        repairType: "Screen",
        date: "02/06/2026",
        slotNo: "1",
        startTime: "02:00",
    },
    {
        clientName: "Jane.D",
        clientPhone: "01960685765",
        clientMail: "admin@gmail.com",
        device: "Apple/Iphone 13pro",
        repairType: "Screen",
        date: "02/06/2026",
        slotNo: "1",
        startTime: "03:00",
    },
    {
        clientName: "Jane.D",
        clientPhone: "01960685765",
        clientMail: "admin@gmail.com",
        device: "Apple/Iphone 13pro",
        repairType: "Screen",
        date: "02/06/2026",
        slotNo: "1",
        startTime: "04:00",
    },
    {
        clientName: "Jane.D",
        clientPhone: "01960685765",
        clientMail: "admin@gmail.com",
        device: "Apple/Iphone 13pro",
        repairType: "Screen",
        date: "02/06/2026",
        slotNo: "1",
        startTime: "04:30",
    },
]

export default tableData